.PHONY: test

test:
	pytest -xv test.py

# learning Make, I put this to run hello2.py with all arguments.
hello2:
	/bin/python3 /home/centos/tiny_python_projects/01_hello/hello2.py hello -a 'man' -i 17 -f /etc/hosts -o
